
name: Test and publish for extension gh-repo-rename

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
     build:

          runs-on:  ${{ matrix.os }}
            strategy:
              matrix:
                os:  [ubuntu-latest, windows-latest, macos-latest]
              node-version: [12.x]

           steps: 
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }} # Will be: "Use Node.js 12.x"
            uses: actions/setup-node@v1 # Install node. See https://github.com/actions/setup-node
            with:
              node-version: ${{ "{{ matrix.node-version" }} }}
              repo-token: ${{ secrets.GH_TOKEN }}
              cache: 'npm'

          - name: "Run test"
            run: npm test
            env:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              CI: true